---
Name: advanced-taxonomies
---
SilverStripe\Admin\ModelAdmin:
  extensions:
    - Chrometoaster\AdvancedTaxonomies\Extensions\LeftAndMainTaxonomyExtension

SilverStripe\Control\Director:
  rules:
    at-taxonomy-overview: Chrometoaster\AdvancedTaxonomies\Controllers\TaxonomyOverviewController

Chrometoaster\AdvancedTaxonomies\Dev\AT4xMigrationTask:
  enable_v4_migration: true

Chrometoaster\AdvancedTaxonomies\Models\TaxonomyTerm:
  InternalOnly: "When enabled, the taxonomy will be available for tagging by authors, and in various CMS configuration settings, but won’t be shown or made directly accessible to users. If disabled, the terms in this taxonomy will be displayed throughout the site as tags, labels and within filter options (e.g. during the listing and searching of content)."
  SingleSelect_Checked_Readonly: "This taxonomy has been permanently configured to prevent more than one term being tagged to any individual content item. Typically, this is due to the mutually exclusive nature of the terms. If you wish to enable multi-select, all tags from the taxonomy must be removed from all content (not recommended). Currently, at least one %s has been tagged, possibly others. You might want to consider creating a new taxonomy instead."
  SingleSelect_Checked: "This taxonomy has been configured to prevent more than one term being tagged to any individual content item. Typically, this is due to the mutually exclusive nature of the terms. As soon as any term from the associated taxonomy is tagged to any content item, this option will become permanently set. As none of the terms have yet been used as tags, you can still disable this option."
  SingleSelect_Readonly: "This taxonomy type has been permanently configured to allow more than one term to be tagged to any individual content item. Typically, this is due to the synergistic nature of the terms. If you wish to enable single select, all tags from this taxonomy must be removed from all content (not recommended). Currently, at least one %s has been tagged, possibly others. You might want to consider creating a new taxonomy instead."
  SingleSelect: "If your taxonomy includes mutually exclusive terms or concepts, you <b>might</b> want to enable this option. It will restrict authors from applying more than one tag at a time to any individual content item. Caution: once enabled, this option is not intended to be turned off again; once content has been tagged with single select taxonomy terms, this option becomes permanently enabled."
  RequiredTypes: "Required taxonomies will prompt admins to select a term from these other taxonomies, too, when this current term is assigned to a page, block or file etc. If required taxonomies are set on the root term, then all descendant terms will inherit the requirements. Inheritance can be manually overridden, and further requirements set, on individual terms."
  Terms: "This is a flattened (non-hierarchical) list of all the descendant terms within this taxonomy. This is useful when you need a quick view of all the terms, as it saves you navigating through multiple child term screens."
  PrimaryConceptClass: "Optional. Uses concept class from the taxonomy type (the root term) by default if it's provided there.<br>When a specific concept class is selected here, it applies only to this term, not to its child terms."

---
Only:
  moduleexists: 'silverstripe/cms'
---
SilverStripe\CMS\Model\SiteTree:
  extensions:
    - Chrometoaster\AdvancedTaxonomies\Extensions\DataObjectTaxonomiesDataExtension
SilverStripe\CMS\Controllers\CMSMain:
  extensions:
    - Chrometoaster\AdvancedTaxonomies\Extensions\LeftAndMainTaxonomyExtension
    - Chrometoaster\AdvancedTaxonomies\Extensions\CMSMainTaxonomyExtension

---
Only:
  moduleexists: 'silverstripe/assets'
---
SilverStripe\Assets\File:
  extensions:
    - Chrometoaster\AdvancedTaxonomies\Extensions\DataObjectTaxonomiesDataExtension

---
Only:
  moduleexists: 'silverstripe/asset-admin'
---
SilverStripe\AssetAdmin\Forms\FileFormFactory:
  extensions:
    - Chrometoaster\AdvancedTaxonomies\Extensions\FileFormFactoryTaxonomyExtension
SilverStripe\AssetAdmin\Controller\AssetAdmin:
  extensions:
    - Chrometoaster\AdvancedTaxonomies\Extensions\LeftAndMainTaxonomyExtension
